### ISSUE TITLE
Function Naming Conventions

### ISSUE THREAD

**Issue by danij** [CruceGameDevel/CruceGame#58]
As C does not allow namespaces, I suggest using modulename_function_name or modulename_functionName as a convention for function names.

**Comment by Paul92** [comment]
I agree. We shall edit the existing code and add this to coding standards, but before that I would like other team members express their oppinion about this.

**Comment by RaduSzasz** [comment]
+1

**Comment by YoNuTzZ** [comment]
+1

**Comment by sarvsav** [comment]
+1 for moduleName_functionName.

**Comment by Paul92** [comment]
As many of us agree with this new naming convention, someone pease change the names of the functions accordingly and document the naming convention in docs/coding-standard.ms.

**Comment by Paul92** [comment]
The name of the functions in round module (not yet merged, in the feature branch round) must be changed too.

**Comment by flavius** [comment]
@Paul92 That should do the merger of that branch, since that branch does "not" exist yet.

**Comment by Paul92** [comment]
But others can not work on that branch (eventually by branching out and mergeing into it)? A feature must be implemented by a single person?

**Comment by flavius** [comment]
Everyone is supposed to fetch develop regularily and take action accordingly, so everyone is up to date with the refactoring that has been done (in theory). Many people can work on a branch, that's true, but my point was addressing the status of this issue (open/closed). And since that "other feature branch" does "not" exist yet, this issue is closed.

Of course, you can define the workflow the other way around, you just have to think what you want. Going the way I've described makes branching out a snap, but it requires more work from the merger. For small features with quick iterations, that shouldn't be a problem though, since `git log develop..myfeature` tells you everything.

I would consider this issue closed.

**Comment by Paul92** [comment]
I got it. But in this case, what would you suggest, in order to make a sort of
to do list for the round module? Mergeing the branch with the unfinished module
is a solution? Or opening issues specifically for that branch for people to work
on it?

**Comment by flavius** [comment]
I suggest
1. Better communication
2. `git fetch`, `git log develop..round` if fetch says something has changed in develop (that's of interest because round is branched off develop) and while in round, `git merge develop`
3. Merging round back into develop when round is ready (you merge develop into round first, you run the tests, you talk to your mates, then you merge round into develop)

I wouldn't misuse issues and git to "fix" the communication issues. You need to talk to one another, and if a team member doesn't fully enjoy working in the team (for whatever reasons), he will feel pressured and he'll give up.

Working in the team should be enjoyable, so make it enjoyable, if you want the team to be productive.

It's all about psychology and emotions, not that much about programming. Also take into account the fact that most of you are students and you're not used to work hard to get to a finished product.
